name: sxtest01
favicon: null
layout_spectrum: 0.787028182996437
typography_spectrum: 0.23280387930572033
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.23496340354904532
  lightness: 0.3945978444535285
  saturation: 0.4503385068383068
  rhythmicContrast: 0.038383535109460354
purpose: []
