name: sxtest01
favicon: null
layout_spectrum: 1
typography_spectrum: 0.47223
title: '123456789'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c9c9c9'
    - '#262626'
    - '#9b9b9b'
    - '#464646'
    - '#e7e7e7'
  brandStrength: 0.6875
  lightness: 0.8125
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
